name: main-testing-workflow
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.2.0
        with:
          # Set always-auth in npmrc.
          always-auth: false
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 14.x
          # File containing the version Spec of the version to use.  Examples: .nvmrc, .node-version.
          node-version-file: .node
          # Target architecture for Node to use. Examples: x86, x64. Will use system architecture by default.
          architecture: x86
          # Set this option if you want the action to check for the latest available version that satisfies the version spec.
          check-latest: false
          # Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN.
          registry-url: false
          # Optional scope for authenticating against scoped registries. Will fall back to the repository owner when using the GitHub Packages registry (https://npm.pkg.github.com/).
          scope: true
          # Used to pull node distributions from node-versions.  Since there's a default, this is typically not supplied by the user.
          token: ${{ github.token }}
          # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.
          cache: npm
          # Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. Supports wildcards or a list of file names for caching multiple dependencies.
          cache-dependency-path: front end\package-lock.json
